package Kamarad;


/**
* Kamarad/KamaradOnline.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 5:17:45 PM GMT
*/

public interface KamaradOnline extends KamaradOnlineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface KamaradOnline
