package Kamarad;


/**
* Kamarad/KamaradAccountDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from kamarad.idl
* Wednesday, March 5, 2014 5:17:45 PM GMT
*/

public final class KamaradAccountDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String unique_id = null;
  public String name = null;
  public String phone_number = null;
  public String address = null;
  public int bank_number = (int)0;
  public float balance = (float)0;
  public float kamarad_credit = (float)0;

  public KamaradAccountDetails ()
  {
  } // ctor

  public KamaradAccountDetails (String _unique_id, String _name, String _phone_number, String _address, int _bank_number, float _balance, float _kamarad_credit)
  {
    unique_id = _unique_id;
    name = _name;
    phone_number = _phone_number;
    address = _address;
    bank_number = _bank_number;
    balance = _balance;
    kamarad_credit = _kamarad_credit;
  } // ctor

} // class KamaradAccountDetails
